<?php

return array (
  'object_version' => '',
  'treedata' => '[{"type":"widget","text":"webmail_azure_token_id","data":{"type":"widget","class":"core\\\\forms\\\\HiddenField","editor":"codegen\\\\form\\\\widgetoptions\\\\HiddenOptionsForm","label":"Hidden field","name":"webmail_azure_token_id"}},{"type":"widget","text":"request_token","data":{"type":"widget","class":"core\\\\forms\\\\HiddenField","editor":"codegen\\\\form\\\\widgetoptions\\\\HiddenOptionsForm","label":"Hidden field","name":"request_token"}},{"type":"container","text":"container-generic: Generic","data":{"type":"container","class":"core\\\\forms\\\\FieldSetContainer","editor":"codegen\\\\form\\\\widgetoptions\\\\ContainerOptionsForm","label":"Generic","name":"container-generic"},"children":[{"type":"widget","text":"description: Description","data":{"type":"widget","class":"core\\\\forms\\\\TextField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextFieldOptionsForm","label":"Description","name":"description"}}]},{"type":"container","text":"container-azure: Azure settings","data":{"type":"container","class":"core\\\\forms\\\\FieldSetContainer","editor":"codegen\\\\form\\\\widgetoptions\\\\ContainerOptionsForm","label":"Azure settings","name":"container-azure"},"children":[{"type":"widget","text":"azure_authorization_url: Authorization url","data":{"type":"widget","class":"core\\\\forms\\\\TextField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextFieldOptionsForm","label":"Authorization url","name":"azure_authorization_url"}},{"type":"widget","text":"azure_token_url: Token url","data":{"type":"widget","class":"core\\\\forms\\\\TextField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextFieldOptionsForm","label":"Token url","name":"azure_token_url"}},{"type":"widget","text":"azure_client_id: Client ID","data":{"type":"widget","class":"core\\\\forms\\\\TextField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextFieldOptionsForm","label":"Client ID","name":"azure_client_id"}},{"type":"widget","text":"azure_client_secret: Client secret","data":{"type":"widget","class":"core\\\\forms\\\\TextField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextFieldOptionsForm","label":"Client secret","name":"azure_client_secret"}},{"type":"widget","text":"return_url: Return url","data":{"type":"widget","class":"core\\\\forms\\\\CopyToClipboardField","label":"Return url","info_text":"Has to be set in Azure","name":"return_url"}}]},{"type":"container","text":"container-status: Status","data":{"type":"container","class":"core\\\\forms\\\\FieldSetContainer","editor":"codegen\\\\form\\\\widgetoptions\\\\ContainerOptionsForm","label":"Status","name":"container-status"},"children":[{"type":"widget","text":"status: Status","data":{"type":"widget","class":"core\\\\forms\\\\HtmlField","label":"Status","editor":"codegen\\\\form\\\\widgetoptions\\\\TextOptionsForm","name":"status"}}]}]',
  'module_name' => 'webmail',
  'form_name' => 'AzureTokenForm',
  'daoClass' => '',
  'key_fields' => 'webmail_azure_token_id',
  'short_description' => '',
);

