<?php
/**
 * CodegenSettings - codegen settings
 * 
 */
namespace codegen;


class CodegenSettings {
    
    protected $ctx;
    
    public function __construct() {
        $this->ctx = \core\Context::getInstance();
    }
    
    
    public function autogenerateDao() {
        return $this->ctx->getSetting('codegen_autogenerate_dao', false) ? true : false;
    }
    
}

