<?php

return array (
  'treedata' => '[{"type":"widget","text":"data","data":{"class":"core\\\\forms\\\\HiddenField","editor":"codegen\\\\form\\\\widgetoptions\\\\HiddenOptionsForm","label":"Hidden field","type":"widget","name":"data"}},{"type":"widget","text":"module_name: Module","data":{"class":"core\\\\forms\\\\SelectField","editor":"codegen\\\\form\\\\widgetoptions\\\\SelectOptionsForm","label":"Module","type":"widget","optionItems":"<? return codegen_map_modules();","name":"module_name"}},{"type":"widget","text":"name: Name","data":{"class":"core\\\\forms\\\\TextField","label":"Name","type":"widget","name":"name"}},{"type":"widget","text":"daoObject: DAO Object","data":{"type":"widget","class":"core\\\\forms\\\\SelectField","editor":"codegen\\\\form\\\\widgetoptions\\\\SelectOptionsForm","label":"DAO Object","name":"daoObject","optionItems":"<?php return codegen_map_dao_classes();"}},{"type":"widget","text":"short_description: Short description","data":{"class":"core\\\\forms\\\\TextField","label":"Short description","type":"widget","name":"short_description"}},{"type":"widget","text":"form_class: Form","data":{"class":"core\\\\forms\\\\SelectField","editor":"codegen\\\\form\\\\widgetoptions\\\\SelectOptionsForm","label":"Form","type":"widget","name":"form_class","optionItems":"<? return array_merge(array(\'\' => \'Make your choice\'), codegen_map_form_classes());\\n"}},{"type":"widget","text":"label: Label","data":{"class":"core\\\\forms\\\\TextField","label":"Label","type":"widget","name":"label","info_text":"Label shown in form where widget is used"}},{"type":"widget","text":"sortable: Sortable","data":{"class":"core\\\\forms\\\\CheckboxField","editor":"codegen\\\\form\\\\widgetoptions\\\\CheckboxOptionsForm","label":"Sortable","type":"widget","name":"sortable"}},{"type":"widget","text":"fields","data":{"class":"codegen\\\\form\\\\ListFormFieldListEdit","editor":"codegen\\\\form\\\\widgetoptions\\\\ListEditWidgetsOptionsForm","label":"codegen\\\\form\\\\ListFormFieldListEdit","type":"widget","name":"fields"}},{"type":"widget","text":"publicfields","data":{"class":"codegen\\\\form\\\\ListFormPublicFieldListEdit","editor":"codegen\\\\form\\\\widgetoptions\\\\ListEditWidgetsOptionsForm","label":"codegen\\\\form\\\\ListFormPublicFieldListEdit","type":"widget","name":"publicfields"}}]',
  'module_name' => 'codegen',
  'form_name' => 'ListFormGeneratorForm',
  'daoClass' => '',
  'key_fields' => '',
  'short_description' => 'codegen - used @ ListFormWidget generator',
);

