<?php

return array (
  'treedata' => '[{"type":"widget","text":"module_name: Module","data":{"type":"widget","class":"core\\\\forms\\\\SelectField","editor":"codegen\\\\form\\\\widgetoptions\\\\SelectOptionsForm","label":"Module","name":"module_name","optionItems":"<? return codegen_map_modules();"}},{"type":"widget","text":"dao_class: DAO Class","data":{"type":"widget","class":"core\\\\forms\\\\SelectField","editor":"codegen\\\\form\\\\widgetoptions\\\\SelectOptionsForm","label":"DAO Class","name":"dao_class","optionItems":"<? return codegen_map_dao_classes();"}},{"type":"widget","text":"controller_name: Controller name","data":{"type":"widget","class":"core\\\\forms\\\\TextField","label":"Controller name","name":"controller_name"}},{"type":"widget","text":"query: Query","data":{"type":"widget","class":"core\\\\forms\\\\TextareaField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextareaOptionsForm","label":"Query","name":"query"}},{"type":"widget","text":"phpcode: Php Code","data":{"type":"widget","class":"core\\\\forms\\\\TextareaField","editor":"codegen\\\\form\\\\widgetoptions\\\\TextareaOptionsForm","label":"Php Code","name":"phpcode","info_text":"Php-code for rendering $row[]","defaultValue":""}},{"type":"widget","text":"html_cols: HTML Columns","data":{"type":"widget","class":"core\\\\forms\\\\HtmlField","label":"HTML Columns","info_text":"HTML rendering code","name":"html_cols"}},{"type":"widget","text":"htmlColumns","data":{"type":"widget","class":"codegen\\\\form\\\\IndexTableColumnListEdit","editor":"codegen\\\\form\\\\widgetoptions\\\\ListEditWidgetsOptionsForm","label":"codegen\\\\form\\\\IndexTableColumnListEdit","name":"htmlColumns"}},{"type":"widget","text":"html_col_web: Columns web-interface","data":{"type":"widget","class":"core\\\\forms\\\\HtmlField","label":"Columns web-interface","name":"html_col_web","defaultValue":"","info_text":"Columns shown in the webinterface"}},{"type":"widget","text":"webColumns","data":{"type":"widget","class":"codegen\\\\form\\\\ListFormFieldListEdit","editor":"codegen\\\\form\\\\widgetoptions\\\\ListEditWidgetsOptionsForm","label":"codegen\\\\form\\\\ListFormFieldListEdit","name":"webColumns","info_text":""}},{"type":"widget","text":"html_colexport: Export Excel","data":{"type":"widget","class":"core\\\\forms\\\\HtmlField","label":"Export Excel","name":"html_colexport","info_text":"Columns shown in exports like Excel & DataSource"}},{"type":"widget","text":"exportColumns","data":{"type":"widget","class":"codegen\\\\form\\\\ListFormFieldListEdit","editor":"codegen\\\\form\\\\widgetoptions\\\\ListEditWidgetsOptionsForm","label":"codegen\\\\form\\\\ListFormFieldListEdit","name":"exportColumns"}}]',
  'module_name' => 'codegen',
  'form_name' => 'IndexTableForm',
  'short_description' => 'Form to generate IndexTable pages',
);

